### ISSUE TITLE
[Information Leakage] No Login check Order Detail

### ISSUE THREAD

**Issue by s1155033765** [ierg4210/shop35#1]
1. Detailed steps to reproduce? Login using test account, open a new tab for inspecting order detail, logout the original tab, refresh new tab
2. What did you see? *Order Detail without login!*
3. What did you expect to see? **Redirect to /account/login**
4. What is the possible fix? **Check if the user is login before rendering the Order Detail**

Image of Proof:

http://i218.photobucket.com/albums/cc176/William_AOE/IERG4210/store35%20info%20leak.png

**Comment by s1155034168** [comment]
Thank you! Fixed
