### ISSUE TITLE
No checking of the list before checkout

### ISSUE THREAD

**Issue by s1155033490** [ierg4210/shop35#2]
1.Detailed steps to reproduce?  visit /checkout?list=null to get the bad gateway
2.What did you see? Without checking the content of the list in line 149 of paypal.api.js
3.What did you expect to see? With a checking of the empty list
4.What is the possible fix? add a if condition

**Comment by s1155034168** [comment]
tutorial10 p.14 > checks on Checkout page > Such as a product which
doesn’t exist in your database

If list = pid not exist in db (e.g 9) or null (means pid not exist in db also), error will be alerted
paypal.api.js:208 res.status(500).end();

**Comment by s1155033490** [comment]
![image](https://cloud.githubusercontent.com/assets/10594688/7513347/10e09b0c-f4e6-11e4-98ad-e5bdd1765f2f.png)

**Comment by hkop2002** [comment]
[TA comment] Paypal should not being proceed with a empty list
