### ISSUE TITLE
MySQL Database not secured.

### ISSUE THREAD

**Issue by ericwong3** [ierg4210/shop35#3]
You should restrict connection to the database to elasticbeanstalk only. Below is a demo where I connected to the MySQL database directly and added a product, this demo product is on your website now.

lx1:/data3/as3n13/wkf113> mysql --user=shop35-admin --password=123456 --host=aaq3zk9icx5y5v.clvba8veoejd.ap-southeast-1.rds.amazonaws.com
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7127
Server version: 5.6.22-log MySQL Community Server (GPL)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use shop35
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT * FROM products
    -> ;
+-----+-------+-------------+--------+--------------+-------+-------+
| pid | catid | name        | price  | description  | thumb | image |
+-----+-------+-------------+--------+--------------+-------+-------+
|   1 |     1 | Rubbish Bin | 100.00 | I am rubbish | jpg   | jpg   |
|   2 |     1 | 689         | 200.00 | I am 689     | jpg   | jpg   |
|   3 |     2 | Broom       | 300.00 | I am broom   | jpg   | jpg   |
|   4 |     2 | Yunchow     | 400.00 | I am yuncho  | jpg   | jpg   |
+-----+-------+-------------+--------+--------------+-------+-------+
4 rows in set (0.05 sec)

mysql> INSERT INTO products (catid, name, price, description) VALUES (2, 'Injection', 'Please secure you database ;)')
    -> ;
ERROR 1136 (21S01): Column count doesn't match value count at row 1
mysql> INSERT INTO products (catid, name, price, description) VALUES (2, 'Injection', 123, 'Please secure you database ;)')
    -> ;
Query OK, 1 row affected (0.10 sec)

![store35](https://cloud.githubusercontent.com/assets/1881669/7533862/8c7d5c52-f5a7-11e4-826b-56c79607ae38.png)

**Comment by s1155034168** [comment]
Thank you!
